apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: {{ .Values.appName }}-secrets
  namespace: {{ .Release.Namespace }}
spec:
  provider: azure
  parameters:
    clientID: "{{ .Values.clientId}}"
    keyvaultName: "{{ .Values.keyVault.name}}"
    objects: |
      array:
        - |
          objectName: SegmentationApiDatabaseConnection
          objectType: secret
        - |
          objectName: ClerkSecretKey
          objectType: secret
        - |
          objectName: ClerkWebhookSecret
          objectType: secret
    tenantID: "{{ .Values.keyVault.tenantId}}"
  secretObjects:
    - secretName: segmentationapicredentials
      type: Opaque
      data:
        - objectName: SegmentationApiDatabaseConnection
          key: DatabaseConnection
    - secretName: clerkcredentials
      type: Opaque
      data:
        - objectName: ClerkSecretKey
          key: SecretKey
        - objectName: ClerkWebhookSecret
          key: WebhookSecret
