apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.appName }}-serviceaccount
  namespace: cdp
  annotations:
    azure.workload.identity/client-id: "{{ .Values.clientId }}"
  labels:
    azure.workload.identity/use: "true"
